/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Prova.Questao2;

import Prova.Questao1.Estadia;
import Prova.Questao1.Periodo;

/**
 *
 * @author Emanuel Sergio Girardi
 */
public class Front extends javax.swing.JFrame {

    private Periodo perido;
    
    /**
     * Creates new form Front
     */
    public Front() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entradaDias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saidaTotal = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        entradaPerido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alertas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Informe a quantidade de dias :");

        entradaDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaDiasActionPerformed(evt);
            }
        });

        jLabel2.setText("VALOR TOTAL:");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        entradaPerido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaPeridoActionPerformed(evt);
            }
        });

        jLabel3.setText("informe a temporada (alta, media ou baixa)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alertas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(saidaTotal)))
                        .addGap(87, 87, 87)
                        .addComponent(entradaDias, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calcular)
                    .addComponent(jLabel3)
                    .addComponent(entradaPerido, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(entradaDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entradaPerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcular)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(saidaTotal))
                .addGap(18, 18, 18)
                .addComponent(alertas)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaDiasActionPerformed

    /**
     @param entradaDias
     @param entradaPerido
     @return retorna o valor a ser pago pela estadia no label saidaTotal
     */
    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        
           alertas.setText("");
   
            try {
             Estadia estadia = new Estadia();
            
            
            if(entradaPerido.getText().equalsIgnoreCase("alta")){
                estadia.setPeriodo(Periodo.ALTA_TEMPORADA);
            }else if(entradaPerido.getText().equalsIgnoreCase("media")){
                estadia.setPeriodo(Periodo.MEDIA_TEMPORADA);
            }else if(entradaPerido.getText().equalsIgnoreCase("baixa")){
                estadia.setPeriodo(Periodo.BAIXA_TEMPORADA);
            } 
            estadia.setQuantidadeDias(Integer.parseInt(entradaDias.getText()));
            saidaTotal.setText("R$"+estadia.precoPagar());
        } catch (Exception e) {
            
            alertas.setText("erro:" + e.getMessage());
            
        }
           
           
            
            
    }//GEN-LAST:event_calcularActionPerformed

    private void entradaPeridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaPeridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaPeridoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertas;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField entradaDias;
    private javax.swing.JTextField entradaPerido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel saidaTotal;
    // End of variables declaration//GEN-END:variables
}
